import { ServiceCategory } from './types';

export const BUSINESS_INFO = {
  name: 'Elite Plumbers Services',
  phone: '020 8015 7153',
  phoneHref: 'tel:+442080157153',
  email: 'info@eliteplumbingservices.co.uk',
  emailHref: 'mailto:info@eliteplumbingservices.co.uk',
  gasSafeReg: '654321',
  vatReg: 'GB122432543',
  insuranceLimit: '£5,000,000 Public Liability',
  guaranteeText: 'All work comes with our exclusive 12-month Elite workmanship guarantee.',
};

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: 'emergency-plumbing',
    slug: 'emergency-plumbing',
    name: 'Emergency Plumbing 🚨',
    emoji: '🚨',
    isEmergency: true,
    shortDescription: 'Our hallmark 30-60 minute rapid response for burst pipes, flooding, blockages or heating breakdowns.',
    services: [
      { id: 'burst-pipe', name: 'Burst Pipe', description: 'Immediate containment and hot/cold line slice repair to prevent water damage.', urgency: 'emergency', estimatedPrice: 'From £95' },
      { id: 'water-leak', name: 'Water Leak', description: 'Emergency isolation and trace-and-repair for high-pressure leaks.', urgency: 'emergency', estimatedPrice: 'From £85' },
      { id: 'overflowing-toilet', name: 'Overflowing Toilet', description: 'Resolving failed cistern ballvalves and overflow pipes immediately.', urgency: 'emergency', estimatedPrice: 'From £80' },
      { id: 'blocked-toilet-emergency', name: 'Blocked Toilet', description: 'Swift mechanical clearing of primary toilets to restore hygiene.', urgency: 'emergency', estimatedPrice: 'From £85' },
      { id: 'blocked-sink-emergency', name: 'Blocked Sink', description: 'Restoring main kitchen or bathroom waste flows and removing fat blocks.', urgency: 'emergency', estimatedPrice: 'From £75' },
      { id: 'no-hot-water-emergency', name: 'No Hot Water', description: 'Priority diagnostics for sudden storage tank or combi hot water outage.', urgency: 'emergency', estimatedPrice: 'From £90' },
      { id: 'boiler-breakdown-emergency', name: 'Boiler Breakdown', description: 'Immediate Gas Safe diagnostic and breakdown fault-code override.', urgency: 'emergency', estimatedPrice: 'From £110' },
      { id: 'flooding', name: 'Flooding', description: 'Emergency pump-out, water removal, and sub-floor pipe integrity testing.', urgency: 'emergency', estimatedPrice: 'Quote on-site' },
      { id: 'emergency-drain-unblock', name: 'Emergency Drain Unblocking', description: 'High-pressure water jetting for outdoor inspection chambers or gullies.', urgency: 'emergency', estimatedPrice: 'From £95' },
      { id: 'twentyfourseven-callout', name: '24/7 Emergency Call Out', description: 'Guaranteed rapid out-of-hours engineer booking with live GPS tracking.', urgency: 'emergency', estimatedPrice: '£125 Flat rate' },
    ],
  },
  {
    id: 'boiler-heating',
    slug: 'boiler-heating',
    name: 'Boiler & Heating Services 🔥',
    emoji: '🔥',
    isEmergency: false,
    shortDescription: 'Gas Safe registered technicians for annual servicing, heat repairs, radiator upgrades, and installs.',
    services: [
      { id: 'boiler-repair', name: 'Boiler Repair', description: 'In-depth diagnostics and replacement of thermistors, diverter valves, or pump units.', urgency: 'same-day', estimatedPrice: 'From £95' },
      { id: 'boiler-installation', name: 'Boiler Installation', description: 'Installation of high-efficiency, A-rated modern systems with up to 12-year warranties.', urgency: 'standard', estimatedPrice: 'From £1,850' },
      { id: 'boiler-replacement', name: 'Boiler Replacement', description: 'Removing outdated systems and matching your home with a premium, quiet heat source.', urgency: 'standard', estimatedPrice: 'From £1,950' },
      { id: 'boiler-service', name: 'Boiler Service', description: 'Annual diagnostic safety, flue gas combustion analysis, and interior clean.', urgency: 'standard', estimatedPrice: '£85 fixed' },
      { id: 'combi-boiler-install', name: 'Combi Boiler Installation', description: 'Bespoke high-output space-saving combination boiler retrofits.', urgency: 'standard', estimatedPrice: 'From £1,890' },
      { id: 'gas-boiler-repair', name: 'Gas Boiler Repair', description: 'Gas line pressure testing, burner cleaning, and combustion resolution.', urgency: 'same-day', estimatedPrice: 'From £110' },
      { id: 'central-heating-repair', name: 'Central Heating Repair', description: 'Fixing central pumps, motorized 2/3 port valves, and programmer errors.', urgency: 'same-day', estimatedPrice: 'From £95' },
      { id: 'central-heating-install', name: 'Central Heating Installation', description: 'Full system sizing design, boiler, pipe drops, and radiator installations.', urgency: 'standard', estimatedPrice: 'Quote on-site' },
      { id: 'radiator-repair', name: 'Radiator Repair', description: 'Fixing pinhole radiator leaks, weeping lockshield valves, and cold spots.', urgency: 'same-day', estimatedPrice: 'From £65' },
      { id: 'radiator-installation', name: 'Radiator Installation', description: 'Sizing, mounting, and connecting ultra-modern vertical or designer convector radiators.', urgency: 'standard', estimatedPrice: 'From £110 + unit' },
      { id: 'power-flushing', name: 'Power Flushing', description: 'Clearing system sludge and magnetite build-up with heavy-duty flushing rigs.', urgency: 'standard', estimatedPrice: 'From £390' },
      { id: 'thermostat-installation', name: 'Thermostat Installation', description: 'Mounting and linking smart Hive, Nest, or Tado terminal controllers.', urgency: 'standard', estimatedPrice: '£120 + controller' },
    ],
  },
  {
    id: 'drainage-services',
    slug: 'drainage-services',
    name: 'Drainage Services 🚿',
    emoji: '🚿',
    isEmergency: false,
    shortDescription: 'Clearing, cleaning, structural surveys and structural repairs of internal and external waste lines.',
    services: [
      { id: 'blocked-drains', name: 'Blocked Drains', description: 'Clearing external main inspection chambers or soil pipes via high-duty jets.', urgency: 'same-day', estimatedPrice: 'From £95' },
      { id: 'blocked-toilet-drain', name: 'Blocked Toilet', description: 'Dismantling and clearing severe deep toilet blockages beyond standard toilet bowls.', urgency: 'same-day', estimatedPrice: '£80 fixed' },
      { id: 'blocked-sink-drain', name: 'Blocked Sink', description: 'Aromatic cleaning and grease/paste extraction from bathroom or kitchen waste traps.', urgency: 'same-day', estimatedPrice: '£75 fixed' },
      { id: 'drain-unblocking', name: 'Drain Unblocking', description: 'General mechanical coil unblocking and root-slice clearances.', urgency: 'same-day', estimatedPrice: 'From £85' },
      { id: 'drain-cleaning', name: 'Drain Cleaning', description: 'Preventative high-flow washdowns to eliminate bad smells and grease layers.', urgency: 'standard', estimatedPrice: 'From £90' },
      { id: 'drain-repair', name: 'Drain Repair', description: 'Excavation repair or structural line replacements for collapsed drains.', urgency: 'standard', estimatedPrice: 'Quote on-site' },
      { id: 'cctv-drain-survey', name: 'CCTV Drain Survey', description: 'High-res waterproof push-rod camera survey with full USB recording for homebuyers.', urgency: 'standard', estimatedPrice: '£140 fixed' },
      { id: 'outside-drain-issues', name: 'Outside Drain Issues', description: 'Repairing cracked gulley grids, overflow rainwater lines, or surface water build-ups.', urgency: 'same-day', estimatedPrice: 'From £95' },
    ],
  },
  {
    id: 'leak-detection',
    slug: 'leak-detection',
    name: 'Leak Detection & Repairs 💧',
    emoji: '💧',
    isEmergency: false,
    shortDescription: 'Trace-and-access pinpointing utilizing non-invasive thermal imaging and acoustic sensors.',
    services: [
      { id: 'water-leak-detection', name: 'Water Leak Detection', description: 'Acoustic sensing and thermal camera trace to locate concealed piping leaks.', urgency: 'same-day', estimatedPrice: 'From £165' },
      { id: 'pipe-leak-repair', name: 'Pipe Leak Repair', description: 'Cutting out copper or MDPE sections and copper-pressing leak joints.', urgency: 'same-day', estimatedPrice: 'From £85' },
      { id: 'underground-leak-detection', name: 'Underground Leak Detection', description: 'Pinpointing buried garden water mains or slab leaks non-destructively.', urgency: 'standard', estimatedPrice: 'Quote on-site' },
      { id: 'ceiling-leak-repair', name: 'Ceiling Leak Repair', description: 'Accessing joist voids, repairing loose multi-skin plastic pipe fittings, and capping joints.', urgency: 'same-day', estimatedPrice: 'From £95' },
      { id: 'kitchen-leak-repair', name: 'Kitchen Leak Repair', description: 'Repairing appliance feed valves, sink baskets, or under-counter waste lines.', urgency: 'same-day', estimatedPrice: 'From £75' },
      { id: 'bathroom-leak-repair', name: 'Bathroom Leak Repair', description: 'Diagnosing weeps beneath baths, showers, vanity traps or toilet cistern seals.', urgency: 'same-day', estimatedPrice: 'From £80' },
      { id: 'water-pressure-problems', name: 'Water Pressure Problems', description: 'Diagnosing PRVs, low flow rates, accumulator sizing, or booster pump installs.', urgency: 'standard', estimatedPrice: 'From £90' },
    ],
  },
  {
    id: 'bathroom-plumbing',
    slug: 'bathroom-plumbing',
    name: 'Bathroom Plumbing 🚽',
    emoji: '🚽',
    isEmergency: false,
    shortDescription: 'Full layout refurbishments, mixer systems, and plumbing for domestic bathroom suites.',
    services: [
      { id: 'bathroom-installation', name: 'Bathroom Installation', description: 'First-fix plumbing, waste lines, and second-fix placement of luxurious sanitary sets.', urgency: 'standard', estimatedPrice: 'Quote on-site' },
      { id: 'bathroom-renovation', name: 'Bathroom Renovation', description: 'Modern restructuring, tiling assistance, updated layouts, and shower conversions.', urgency: 'standard', estimatedPrice: 'Quote on-site' },
      { id: 'shower-installation', name: 'Shower Installation', description: 'Installing power showers, electric water booster showers, or thermostatic rainfall bars.', urgency: 'standard', estimatedPrice: 'From £180 + unit' },
      { id: 'shower-repair', name: 'Shower Repair', description: 'Replacing failing cartridges, thermostatic balancing valves, or shower glass seals.', urgency: 'same-day', estimatedPrice: 'From £85' },
      { id: 'toilet-installation', name: 'Toilet Installation', description: 'Sizing and installing modern close-coupled, back-to-wall, or wall-hung toilets.', urgency: 'standard', estimatedPrice: 'From £130 + unit' },
      { id: 'toilet-repair', name: 'Toilet Repair', description: 'Fixing faulty syphon diaphragms, filling inlet valves, or leaky wax pan seals.', urgency: 'same-day', estimatedPrice: 'From £80' },
      { id: 'bath-installation', name: 'Bath Installation', description: 'Sizing, support framing, and sealing of high-grade single/double-ended baths or freestanding tubs.', urgency: 'standard', estimatedPrice: 'From £220 + unit' },
      { id: 'bathroom-pipework', name: 'Bathroom Pipework', description: 'Rearranging plastic push-fit or speedfit supply feeds, and copper waste routes.', urgency: 'standard', estimatedPrice: 'From £95' },
      { id: 'wet-room-installation', name: 'Wet Room Installation', description: 'Tanking/waterproofing systems, floor grading adapters, linear drains, and fixtures.', urgency: 'standard', estimatedPrice: 'Quote on-site' },
    ],
  },
  {
    id: 'kitchen-plumbing',
    slug: 'kitchen-plumbing',
    name: 'Kitchen Plumbing 🚰',
    emoji: '🚰',
    isEmergency: false,
    shortDescription: 'Practical sink, tap, filter, dishwasher, and washing machine connections.',
    services: [
      { id: 'kitchen-sink-installation', name: 'Kitchen Sink Installation', description: 'Piping composite, stainless steel, or Belfast sinks clean within countertops.', urgency: 'standard', estimatedPrice: 'From £110 + sink' },
      { id: 'kitchen-tap-installation', name: 'Kitchen Tap Installation', description: 'Installing modern pull-out sprays, boiling hot-water kettles, or standard mixers.', urgency: 'standard', estimatedPrice: 'From £75' },
      { id: 'tap-repair', name: 'Tap Repair', description: 'Resending ceramic discs, replacing leaking body gaskets or upgrading tap spouts.', urgency: 'same-day', estimatedPrice: 'From £65' },
      { id: 'dishwasher-installation', name: 'Dishwasher Installation', description: 'Connecting cold water valves, tailoring waste standpipes, and levelling units.', urgency: 'standard', estimatedPrice: '£70 flat rate' },
      { id: 'washing-machine-installation', name: 'Washing Machine Installation', description: 'Installing flexible feed lines, water restrictors, and testing output waste pump flows.', urgency: 'standard', estimatedPrice: '£70 flat rate' },
      { id: 'waste-disposal-installation', name: 'Waste Disposal Installation', description: 'Plumbing high-grade electric food waste sink shredder units below main bowls.', urgency: 'standard', estimatedPrice: 'From £115 + unit' },
      { id: 'water-filter-installation', name: 'Water Filter Installation', description: 'Fitting multi-stage under-sink filtration sets with dedicated mini-taps.', urgency: 'standard', estimatedPrice: 'From £85' },
    ],
  },
  {
    id: 'gas-services',
    slug: 'gas-services',
    name: 'Gas Services 🔥',
    emoji: '🔥',
    isEmergency: false,
    shortDescription: 'Gas Safe checks, CP12 certifications, cooker hookups and appliance safety surveys.',
    services: [
      { id: 'gas-safety-certificate', name: 'Gas Safety Certificate (CP12)', description: 'Official annual Gas Safe appraisal for up to 3 gas appliances, logs submitted online.', urgency: 'standard', estimatedPrice: '£75 fixed' },
      { id: 'gas-appliance-installation', name: 'Gas Appliance Installation', description: 'Validating gas pressures and safely piping modern gas fires or space boilers.', urgency: 'standard', estimatedPrice: 'From £120' },
      { id: 'gas-leak-detection', name: 'Gas Leak Detection', description: 'Gas pressure drop tightness testing, locating minute leaks using visual bubble agents.', urgency: 'same-day', estimatedPrice: 'From £110' },
      { id: 'landlord-gas-safety-cert', name: 'Landlord Gas Safety Certificate', description: 'CP12 documentation with digital tenant copies, automatic annual booking alerts.', urgency: 'standard', estimatedPrice: '£75 fixed' },
      { id: 'gas-pipe-installation', name: 'Gas Pipe Installation', description: 'Running new thick-wall copper gas lines or black-iron pipe drops securely.', urgency: 'standard', estimatedPrice: 'Quote on-site' },
      { id: 'gas-cooker-installation', name: 'Gas Cooker Installation', description: 'Screwing bayonet hoses, fixing stability chains, and validating flame failures on hobs.', urgency: 'standard', estimatedPrice: '£85 fixed rate' },
    ],
  },
  {
    id: 'pipework-services',
    slug: 'pipework-services',
    name: 'Pipework Services 🔧',
    emoji: '🔧',
    isEmergency: false,
    shortDescription: 'First-rate copper pressing, frozen pipe isolation and main stopcock upgrades.',
    services: [
      { id: 'pipe-repair-general', name: 'Pipe Repair', description: 'Soldering or pressing leaking plumbing pipes, fixing copper pinhole corrosion.', urgency: 'same-day', estimatedPrice: 'From £80' },
      { id: 'pipe-replacement', name: 'Pipe Replacement', description: 'Replacing degrading grey polybutylene pipes with modern barrier PEX lines.', urgency: 'standard', estimatedPrice: 'Quote on-site' },
      { id: 'frozen-pipe-repair', name: 'Frozen Pipe Repair', description: 'Careful systemic expansion thawing to trace micro-fractures before flooding occurs.', urgency: 'same-day', estimatedPrice: 'From £100' },
      { id: 'water-main-repair', name: 'Water Main Repair', description: 'Trench-free moling or external replacement of underground MDPE water main lines.', urgency: 'standard', estimatedPrice: 'Quote on-site' },
      { id: 'new-pipe-installation', name: 'New Pipe Installation', description: 'Piping water supplies to external garden cabins, loft expansions, or utility layouts.', urgency: 'standard', estimatedPrice: 'From £120' },
      { id: 'pipe-insulation', name: 'Pipe Insulation', description: 'Lagging loft plumbing or exterior lines with frost-rated insulation jackets.', urgency: 'standard', estimatedPrice: 'From £50' },
    ],
  },
  {
    id: 'property-landlord',
    slug: 'property-landlord',
    name: 'Property & Landlord Services 🏠',
    emoji: '🏠',
    isEmergency: false,
    shortDescription: 'Dedicated property audit packages, letting agency repair SLAs, and water integrity protocols.',
    services: [
      { id: 'landlord-plumbing-inspection', name: 'Landlord Plumbing Inspection', description: 'Full status reviews of kitchen waste feeds, bath sealing, and stopcocks.', urgency: 'standard', estimatedPrice: 'From £95' },
      { id: 'cp12-certificate-combo', name: 'CP12 Certificate', description: 'Fast certification checks structured specifically for remote landlords.', urgency: 'standard', estimatedPrice: '£75 fixed' },
      { id: 'property-maintenance', name: 'Property Maintenance', description: 'Continuous quarterly inspections and minor leak rectifications.', urgency: 'standard', estimatedPrice: 'Quote on contract' },
      { id: 'rental-property-repairs', name: 'Rental Property Repairs', description: 'Coordinating repair steps direct with block management keys and tenants.', urgency: 'same-day', estimatedPrice: 'From £85' },
      { id: 'end-of-tenancy-check', name: 'End Of Tenancy Plumbing Check', description: 'Verification that waste flows, flushes, and boiler pressures are compliant before handovers.', urgency: 'standard', estimatedPrice: '£90 fixed' },
    ],
  },
  {
    id: 'commercial-plumbing',
    slug: 'commercial-plumbing',
    name: 'Commercial Plumbing 🏢',
    emoji: '🏢',
    isEmergency: false,
    shortDescription: 'Heavy-duty commercial systems, office facilities maintenance, and grease interceptors.',
    services: [
      { id: 'office-plumbing', name: 'Office Plumbing', description: 'Commercial tea point setups, sensor tap installations, and multi-cubicle toilet blocks.', urgency: 'standard', estimatedPrice: 'Quote on-site' },
      { id: 'restaurant-plumbing', name: 'Restaurant Plumbing', description: 'Accredited grease-trap setups, high-temperature dishwasher feeds, and compliance traps.', urgency: 'standard', estimatedPrice: 'From £150' },
      { id: 'shop-plumbing', name: 'Shop Plumbing', description: 'Water heater feeds, micro-toilet plumbing, and retail supply reroutes.', urgency: 'standard', estimatedPrice: 'From £110' },
      { id: 'school-plumbing', name: 'School Plumbing', description: 'Vandal-resistant fixtures, safety thermostatic mixing valves (TMVs), and sports showers.', urgency: 'standard', estimatedPrice: 'Quote on-site' },
      { id: 'hotel-plumbing', name: 'Hotel Plumbing', description: 'Maintaining hot water ring-mains, high-pressure booster systems, and guest room repairs.', urgency: 'standard', estimatedPrice: 'Quote on-site' },
      { id: 'commercial-boiler-service', name: 'Commercial Boiler Service', description: 'Gas Safe inspection of heating plants exceeding 70kW, combustion logs provided.', urgency: 'standard', estimatedPrice: 'From £220' },
      { id: 'commercial-drain-cleaning', name: 'Commercial Drain Cleaning', description: 'Regular preventative electro-mechanical cabling of block commercial grease gullies.', urgency: 'standard', estimatedPrice: 'From £150' },
      { id: 'commercial-maintenance-contracts', name: 'Commercial Maintenance Contracts', description: 'Fixed SLAs offering guaranteed four-hour emergency engineer response windows.', urgency: 'standard', estimatedPrice: 'SLA Custom Quote' },
    ],
  },
  {
    id: 'others',
    slug: 'others',
    name: 'Others 🔧',
    emoji: '🔧',
    isEmergency: false,
    shortDescription: 'Miscellaneous plumbing works, custom requests, thermal sweeps, and bespoke repairs.',
    services: [
      { id: 'water-softener-install', name: 'Water Softener Installation', description: 'Installing high-grade ion-exchange water softeners to protect pipe grids.', urgency: 'standard', estimatedPrice: 'From £160 + unit' },
      { id: 'mains-stopcock-upgrade', name: 'Main Stopcock Replacement', description: 'Replacing seized brass stopcocks with lever valves or Surestop remote flow switches.', urgency: 'standard', estimatedPrice: 'From £95' },
      { id: 'garden-tap-installation', name: 'Outdoor Garden Tap Fitting', description: 'Tapping main copper lines, installing double check valves, and exterior copper bibtaps.', urgency: 'standard', estimatedPrice: '£85 fixed rate' },
      { id: 'custom-pressure-test', name: 'Custom Pressure Diagnostics', description: 'Calibrated hydrostatic water testing to diagnose pipe network pressure leaks.', urgency: 'standard', estimatedPrice: 'From £110' },
      { id: 'bespoke-fitting-repair', name: 'Other General Plumbing issue', description: 'Other non-standard plumbing fixtures, lead pipe diagnostics, or custom requests.', urgency: 'standard', estimatedPrice: 'Quote on-site' },
    ],
  },
];

export const TESTIMONIALS = [
  {
    name: 'Eleanor Vance',
    location: 'Wimbledon, SW19',
    rating: 5,
    text: 'Elite Plumbing Services saved my weekend! A massive pipe burst under my kitchen sink around 10 PM. The technician was at my door in 35 minutes, isolated the leak, and replaced the cracked section. Extremely professional and fair pricing for a late-night emergency.',
    date: '2 weeks ago',
  },
  {
    name: 'Marcus Thorne',
    location: 'Greenwich, SE10',
    rating: 5,
    text: 'Highly recommend their Landlord Gas Safety combo. They scheduled the CP12 inspection and boiler service with my tenant directly, arrived on time, and emailed me the certificate immediately. Efficient, professional, and transparent pricing.',
    date: '1 month ago',
  },
  {
    name: 'Sarah Jenkins',
    location: 'Hampstead, NW3',
    rating: 5,
    text: 'Our old combi boiler broke down right as winter hit. Elite provided a quote within 24 hours and had a brand new Worcester Bosch boiler installed and running 2 days later. A clean, efficient team. The 10-year warranty is a huge peace of mind!',
    date: '3 weeks ago',
  },
  {
    name: 'David Patel',
    location: 'Clapham, SW4',
    rating: 5,
    text: 'Used them to clear a blocked outside drain. They did a high-pressure jetting and used a camera to show me some tree root damage, which we then patched. No extra hidden costs. Great communication throughout.',
    date: '2 months ago',
  },
];

export const POSTCODE_AREAS = [
  // West & Central
  { code: 'W1', area: 'Mayfair, Soho, Marylebone', covered: true },
  { code: 'W2', area: 'Bayswater, Paddington', covered: true },
  { code: 'WC1', area: 'Bloomsbury, Gray\'s Inn', covered: true },
  { code: 'WC2', area: 'Covent Garden, Strand', covered: true },
  { code: 'EC1', area: 'Clerkenwell, Farringdon', covered: true },
  { code: 'EC2', area: 'Bishopsgate, Shoreditch', covered: true },
  // Southwest
  { code: 'SW1', area: 'Westminster, Belgravia', covered: true },
  { code: 'SW2', area: 'Brixton, Streatham Hill', covered: true },
  { code: 'SW3', area: 'Chelsea, Brompton', covered: true },
  { code: 'SW4', area: 'Clapham', covered: true },
  { code: 'SW5', area: 'Earls Court', covered: true },
  { code: 'SW6', area: 'Fulham, Parsons Green', covered: true },
  { code: 'SW7', area: 'South Kensington', covered: true },
  { code: 'SW8', area: 'South Lambeth, Nine Elms', covered: true },
  { code: 'SW11', area: 'Battersea, Clapham Junction', covered: true },
  { code: 'SW15', area: 'Putney, Roehampton', covered: true },
  { code: 'SW18', area: 'Wandsworth, Earlsfield', covered: true },
  { code: 'SW19', area: 'Wimbledon, Colliers Wood', covered: true },
  // Northwest
  { code: 'NW1', area: 'Camden Town, Regent\'s Park', covered: true },
  { code: 'NW3', area: 'Hampstead, Belsize Park', covered: true },
  { code: 'NW6', area: 'Kilburn, Queens Park', covered: true },
  { code: 'NW8', area: 'St John\'s Wood', covered: true },
  // North
  { code: 'N1', area: 'Islington, Barnsbury', covered: true },
  { code: 'N5', area: 'Highbury', covered: true },
  { code: 'N7', area: 'Holloway', covered: true },
  { code: 'N19', area: 'Archway', covered: true },
  // East
  { code: 'E1', area: 'Whitechapel, Stepney', covered: true },
  { code: 'E2', area: 'Bethnal Green, Hackney', covered: true },
  { code: 'E14', area: 'Canary Wharf, Isle of Dogs', covered: true },
  // Southeast
  { code: 'SE1', area: 'Southwark, Bermondsey', covered: true },
  { code: 'SE10', area: 'Greenwich', covered: true },
  { code: 'SE11', area: 'Kennington', covered: true },
  { code: 'SE15', area: 'Peckham, Nunhead', covered: true },
];

export const CERTIFICATIONS = [
  { title: 'Gas Safe Registered', subtitle: 'License #654321', desc: 'Legally qualified to work on gas lines, boilers, and appliances safely.' },
  { title: 'City & Guilds Qualified', subtitle: 'Advanced Plumber Craft', desc: 'Trained to the peak level of technical precision and sanitary sciences.' },
  { title: 'Checkatrade Approved', subtitle: 'Score: 9.9/10 (220+ Reviews)', desc: 'Vetted, continuously monitored for high standards and reliability.' },
  { title: 'WaterSafe Approved', subtitle: 'Clean Water Standards', desc: 'Certified to meet the strict UK Water Supply Regulations.' },
];
